---

- name: Create override directory for firewalld systemd service
  ansible.builtin.file:
    path: "/etc/systemd/system/firewalld.service.d"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create override file for firewalld systemd service
  ansible.builtin.template:
    src: firewalld.override.j2
    dest: "/etc/systemd/system/firewalld.service.d/localhost_ssh.conf"
    mode: '0644'
    owner: root
    group: root
  notify: (Re)start firewalld service

- name: Install firewall packages
  ansible.builtin.package:
    name:
      - firewalld
      - python3-firewall
    state: present

- name: FirewallD input services
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    service: "{{ item.service }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: true
    immediate: true
  with_items: "{{ firewalld.input.services | default([]) }}"

- name: FirewallD input ports
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    port: "{{ item.port }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: true
    immediate: true
  with_items: "{{ firewalld.input.ports | default([]) }}"

- name: FirewallD port forward
  ansible.posix.firewalld:
    port_forward:
      - port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        toaddr: "{{ item.toaddr | default('') }}"
        toport: "{{ item.toport | default(item.port) }}"
    zone: "{{ item.zone }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: true
    immediate: true
  with_items: "{{ firewalld.forward_ports | default([]) }}"

- name: FirewallD interfaces
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    interface: "{{ item.interface }}"
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{ firewalld.interfaces | default([]) }}"
